site_name: Apple Home Dashboard
site_description: Apple Home inspired dashboard strategy for Home Assistant
site_url: https://nitaybz.github.io/apple-home-dashboard/
repo_url: https://github.com/nitaybz/apple-home-dashboard
repo_name: nitaybz/apple-home-dashboard
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Basic Setup: getting-started/basic-setup.md
  - Configuration:
      - Options: options/index.md
  - FAQ: faq.md
  - Contributing:
      - Guide: contributing/index.md
      - Translations: contributing/translations.md
