name: Bug report
description: Create a report to help us improve
title: "[BUG] - "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Please make sure you have read the [README](https://github.com/nitaybz/apple-home-dashboard/blob/main/README.md) and checked existing issues before submitting a new bug report.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting a bug report
      options:
        - label: I have read the README and documentation
          required: true
        - label: I have searched existing issues for similar problems
          required: true
        - label: I am using a supported version of Home Assistant
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Tell us what you expected
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: "2024.7.0"
    validations:
      required: true

  - type: input
    id: dashboard-version
    attributes:
      label: Apple Home Dashboard Version
      description: What version of Apple Home Dashboard are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Browser Console Logs
      description: Please provide any relevant console logs or error messages
      placeholder: |
        Open browser developer tools (F12) and paste any error messages from the console here.
        Include timestamps if possible.
      render: text

  - type: textarea
    id: config
    attributes:
      label: Dashboard Configuration
      description: Please provide your dashboard configuration (remove any sensitive information)
      placeholder: |
        strategy:
          type: custom:apple-home-strategy
        views: []
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable
      placeholder: Any additional information that might help us understand the issue
