name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] - "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
        Please make sure you have searched existing issues and discussions to see if your idea has already been suggested.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting a feature request
      options:
        - label: I have read the README and documentation
          required: true
        - label: I have searched existing issues for similar feature requests
          required: true
        - label: This feature would benefit the Apple Home Dashboard community
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: I considered...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for usability
        - Critical - Blocking current usage
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - UI/UX Design
        - Card Functionality
        - Dashboard Layout
        - Home Assistant Integration
        - Configuration Options
        - Performance
        - Accessibility
        - Mobile/Responsive
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here
      placeholder: Any additional information that might help us understand your request
